---
- hosts: all
  sudo: true
  vars:
    doc_root: /vagrant/web
    sys_packages: [ 'curl', 'vim', 'git']
    php_packages: [ 'php5-curl', 'php5-cli' ]
  tasks:
    - include: tasks/init.yml
    - include: tasks/nginxphp.yml
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted